insert into public.timeline_entries (
  title,
  slug,
  event_date,
  date_precision,
  era,
  summary,
  story,
  quote,
  tags,
  featured,
  published,
  status,
  sort_year,
  sort_month,
  sort_day
) values
  (
    'Annie Arrives',
    'annie-arrives',
    '1947-03-04',
    'exact',
    'Early Years',
    'Andrea "Andy" Murphy enters the world and immediately begins a lifelong commitment to strong opinions, excellent commentary, and keeping everybody in line.',
    'This entry is sample archive content. Replace it with the family-approved version when the real timeline is ready.',
    'Some stories begin with a date. This one begins with a personality.',
    array['sample', 'early-years', 'family-lore'],
    true,
    true,
    'published',
    1947,
    3,
    4
  ),
  (
    'The Birth of Her Greatest Rival',
    'birth-of-her-greatest-rival',
    '1973-04-01',
    'month',
    'Family Lore',
    'A new chapter arrives, bringing love, comedy, competition, and the kind of lifelong banter that deserves its own exhibit label.',
    'This sample entry gives the timeline a second milestone with a month-and-year date precision.',
    'Every great story needs a worthy rival.',
    array['sample', 'family-lore', 'running-jokes'],
    false,
    true,
    'published',
    1973,
    4,
    null
  ),
  (
    'The Charlotte Era Begins',
    'charlotte-era-begins',
    '2013-10-01',
    'month',
    'Charlotte',
    'A new city opens a new chapter: routines, visitors, local discoveries, and the stories that made Charlotte part of the family archive.',
    'Use this sample to model entries that represent a place-based era rather than a single-day event.',
    'A new city, but the same unmistakable commentary.',
    array['sample', 'charlotte', 'era'],
    true,
    true,
    'published',
    2013,
    10,
    null
  ),
  (
    'The Daily Question Era',
    'daily-question-era',
    null,
    'era',
    'The Daily Question Era',
    'Some memories are not tied to one date. They become rituals: familiar questions, perfect timing, and the feeling that the day has officially started.',
    'This sample demonstrates era-style timeline entries without an exact date.',
    'The question changed shape, but the ritual stayed the same.',
    array['sample', 'daily-question', 'rituals'],
    false,
    true,
    'published',
    2026,
    null,
    null
  )
on conflict (slug) do update set
  title = excluded.title,
  event_date = excluded.event_date,
  date_precision = excluded.date_precision,
  era = excluded.era,
  summary = excluded.summary,
  story = excluded.story,
  quote = excluded.quote,
  tags = excluded.tags,
  featured = excluded.featured,
  published = excluded.published,
  status = excluded.status,
  sort_year = excluded.sort_year,
  sort_month = excluded.sort_month,
  sort_day = excluded.sort_day,
  updated_at = now();
